In [2]:
from google.colab import drive
drive.mount('/gdrive', force_remount = True)

Mounted at /gdrive


In [1]:
# 1. 데이터
import numpy as np
import pandas as pd

dust_data = pd.read_csv('/gdrive/My Drive/Colab Notebooks/dust_project/DataSet.csv')


In [2]:
# minmaxscaler

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler_cols = ['SO2', 'CO',	'O3',	'NO2', 'PM10', 'PM25', 'Temp', 'Prec', 'WS', 'Humi', 'Pres', 'cbwd']
df_scaled = scaler.fit_transform(dust_data[scaler_cols])
df_scaled = pd.DataFrame(df_scaled)
df_scaled.columns = scaler_cols
df_scaled.head()

SO2        CO        O3  ...      Humi      Pres      cbwd
0  0.352490  0.249428  0.137538  ...  0.268015  0.771167  0.794118
1  0.406130  0.242563  0.103811  ...  0.268015  0.771167  0.794118
2  0.570881  0.276888  0.144985  ...  0.268015  0.771167  0.794118
3  0.490421  0.183066  0.105563  ...  0.268015  0.771167  0.794118
4  0.245211  0.217391  0.203241  ...  0.268015  0.771167  0.794118

[5 rows x 12 columns]

In [3]:
x = df_scaled[['Temp', 'Prec', 'WS', 'Humi', 'Pres', 'cbwd']]
y = df_scaled[['SO2', 'CO',	'O3',	'NO2', 'PM10', 'PM25']]

print(x)
print(y)

           Temp  Prec        WS      Humi      Pres      cbwd
0      0.278351   0.0  0.148148  0.268015  0.771167  0.794118
1      0.278351   0.0  0.148148  0.268015  0.771167  0.794118
2      0.278351   0.0  0.148148  0.268015  0.771167  0.794118
3      0.278351   0.0  0.148148  0.268015  0.771167  0.794118
4      0.278351   0.0  0.148148  0.268015  0.771167  0.794118
...         ...   ...       ...       ...       ...       ...
43531  0.121649   0.0  0.333333  0.455120  0.739130  0.735294
43532  0.121649   0.0  0.333333  0.455120  0.739130  0.735294
43533  0.121649   0.0  0.333333  0.455120  0.739130  0.735294
43534  0.121649   0.0  0.333333  0.455120  0.739130  0.735294
43535  0.121649   0.0  0.333333  0.455120  0.739130  0.735294

[43536 rows x 6 columns]
            SO2        CO        O3       NO2      PM10      PM25
0      0.352490  0.249428  0.137538  0.215782  0.131999  0.110623
1      0.406130  0.242563  0.103811  0.297764  0.207082  0.124511
2      0.570881  0.276888  0.144

In [5]:
# print("------numpy change-------")
x = x.to_numpy()
y = y.to_numpy()

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, test_size=0.5)

In [9]:
print(x_train)
x_train.shape


[[0.77113402 0.5771096  0.01851852 0.97977244 0.32951945 0.08823529]
 [0.48041237 0.         0.46296296 0.32743363 0.66819222 0.73529412]
 [0.38762887 0.         0.16666667 0.482933   0.64530892 0.52941176]
 ...
 [0.35876289 0.         0.2037037  0.61567636 0.69336384 0.79411765]
 [0.44123711 0.         0.25925926 0.58280657 0.81235698 0.79411765]
 [0.70103093 0.         0.2962963  0.22629583 0.5194508  0.73529412]]


(26121, 6)

In [11]:


# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
#model.add(Dense(10, input_shape=(10, ), activation='relu'))
model.add(Dense(10, input_dim=(6), activation='relu'))
#model.add(Dense(10))
#model.add(Dense(8))
model.add(Dense(1))
 
# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=20, batch_size=1, validation_data=(x_val, y_val))


Epoch 1/20
26121/26121 [==============================] - 33s 1ms/step - loss: 0.0142 - mse: 0.0142 - val_loss: 0.0136 - val_mse: 0.0136
Epoch 2/20
26121/26121 [==============================] - 36s 1ms/step - loss: 0.0132 - mse: 0.0132 - val_loss: 0.0133 - val_mse: 0.0133
Epoch 3/20
26121/26121 [==============================] - 36s 1ms/step - loss: 0.0130 - mse: 0.0130 - val_loss: 0.0132 - val_mse: 0.0132
Epoch 4/20
26121/26121 [==============================] - 36s 1ms/step - loss: 0.0130 - mse: 0.0130 - val_loss: 0.0131 - val_mse: 0.0131
Epoch 5/20
26121/26121 [==============================] - 32s 1ms/step - loss: 0.0130 - mse: 0.0130 - val_loss: 0.0131 - val_mse: 0.0131
Epoch 6/20
26121/26121 [==============================] - 33s 1ms/step - loss: 0.0129 - mse: 0.0129 - val_loss: 0.0130 - val_mse: 0.0130
Epoch 7/20
26121/26121 [==============================] - 33s 1ms/step - loss: 0.0129 - mse: 0.0129 - val_loss: 0.0130 - val_mse: 0.0130
Epoch 8/20
26121/26121 [=================

In [12]:

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print('acc : ', mse)
 
y_predict = model.predict(x_test)
print(y_predict)
 
# RMSE 구하기
from sklearn.metrics import mean_squared_error
def RMSE(y_test, y_predict):
    return np.sqrt(mean_squared_error(y_test, y_predict))
print('RMSE : ', RMSE(y_test, y_predict)) 
 
# R2 구하기
from sklearn.metrics import r2_score
r2_y_predict = r2_score(y_test, y_predict)
print('R2 : ', r2_y_predict)

8707/8707 [==============================] - 8s 960us/step - loss: 0.0130 - mse: 0.0130
acc :  0.01295155193656683
[[0.22650978]
 [0.16460331]
 [0.22961484]
 ...
 [0.2875781 ]
 [0.25837883]
 [0.21078095]]


ValueError: ignored